---
swagger: "2.0"
info:
  version: "2018-01-20T14:20:20Z"
  title: "PITS"
host: "example.com"
basePath: "/v1"
schemes:
- "https"
paths:
  /auth:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthUrl"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Session"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
  /auth/{type}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "path"
        required: true
        type: "string"
      - name: "code"
        in: "query"
        required: false
        type: "string"
      - name: "error"
        in: "query"
        required: false
        type: "string"
      - name: "nonce"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /devices:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/DeviceList"
      security:
      - OAuthAuthorizer: []
  /devices/{id}:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Device"
      security:
      - OAuthAuthorizer: []
  /devices/{id}/registration:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/AuthUrl"
    put:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "code"
        in: "query"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "Device"
        required: true
        schema:
          $ref: "#/definitions/Device"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /me:
    get:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/User"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
      security:
      - OAuthAuthorizer: []
securityDefinitions:
  OAuthAuthorizer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
  User:
    type: "object"
    properties:
      emailAddress:
        type: "string"
        format: "email"
      firstName:
        type: "string"
      lastName:
        type: "string"
      image:
        type: "string"
        format: "url"
    title: "User schema"
  Device:
    type: "object"
    properties:
      deviceId:
        type: "string"
      macAddress:
        type: "string"
      version:
        type: "string"
      lastUpdate:
        type: "string"
        format: "date-time"
    title: "Device schema"
  AuthUrl:
    type: "object"
    properties:
      authUrl:
        type: "string"
        format: "url"
    title: "Auth URL schema"
  DeviceList:
    title: "Device List schema"
    type: "array"
    items:
      $ref: "#/definitions/DeviceListItem"
  DeviceListItem:
    type: "object"
    properties:
      deviceId:
        type: "string"
      macAddress:
        type: "string"
      version:
        type: "string"
      lastUpdate:
        type: "string"
        format: "date-time"
  Session:
    type: "object"
    properties:
      accessToken:
        type: "string"
      refreshToken:
        type: "string"
      clientId:
        type: "string"
      expiresIn:
        type: "integer"
    title: "Session schema"
